/**
 * CineBook v2 — Movies Dataset (Demo Data)
 */

import { Movie } from "@/types";

export interface MovieDetail extends Movie {
  cast: Array<{ name: string; role: string; image?: string }>;
  director: string;
  trailerYoutubeId?: string;
  format: string[];
  isNowShowing: boolean;
  isUpcoming: boolean;
  upcomingCategory?: "today" | "tomorrow" | "this-weekend" | "weekend" | "soon";
}

export const MOVIES: MovieDetail[] = [
  {
    id: "dune-part-two",
    title: "Dune: Part Two",
    overview: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the universe, he endeavors to prevent a terrible future.",
    posterPath: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80",
    genres: ["Sci-Fi", "Adventure", "Action"],
    durationMinutes: 166,
    rating: 8.8,
    language: "English",
    certificate: "UA 16+",
    releaseDate: "2024-03-01",
    basePrice: 320,
    isFeatured: true,
    isNowShowing: true,
    isUpcoming: false,
    format: ["2D", "IMAX 2D", "4DX"],
    director: "Denis Villeneuve",
    cast: [
      { name: "Timothée Chalamet", role: "Paul Atreides" },
      { name: "Zendaya", role: "Chani" },
      { name: "Rebecca Ferguson", role: "Lady Jessica" },
      { name: "Javier Bardem", role: "Stilgar" },
    ],
  },
  {
    id: "oppenheimer",
    title: "Oppenheimer",
    overview: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during the Manhattan Project.",
    posterPath: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=500&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=1200&auto=format&fit=crop&q=80",
    genres: ["Drama", "History", "Thriller"],
    durationMinutes: 180,
    rating: 8.9,
    language: "English",
    certificate: "A",
    releaseDate: "2023-07-21",
    basePrice: 350,
    isFeatured: true,
    isNowShowing: true,
    isUpcoming: false,
    format: ["2D", "IMAX 70mm", "Dolby Atmos"],
    director: "Christopher Nolan",
    cast: [
      { name: "Cillian Murphy", role: "J. Robert Oppenheimer" },
      { name: "Emily Blunt", role: "Katherine Oppenheimer" },
      { name: "Matt Damon", role: "Leslie Groves" },
      { name: "Robert Downey Jr.", role: "Lewis Strauss" },
    ],
  },
  {
    id: "spider-man-across-the-spider-verse",
    title: "Spider-Man: Across the Spider-Verse",
    overview: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
    posterPath: "https://images.unsplash.com/photo-1635805737707-575885ab0820?w=500&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1200&auto=format&fit=crop&q=80",
    genres: ["Animation", "Action", "Sci-Fi"],
    durationMinutes: 140,
    rating: 8.7,
    language: "English",
    certificate: "U",
    releaseDate: "2023-06-02",
    basePrice: 280,
    isFeatured: true,
    isNowShowing: true,
    isUpcoming: false,
    format: ["2D", "3D", "4DX 3D"],
    director: "Joaquim Dos Santos, Kemp Powers",
    cast: [
      { name: "Shameik Moore", role: "Miles Morales (voice)" },
      { name: "Hailee Steinfeld", role: "Gwen Stacy (voice)" },
      { name: "Oscar Isaac", role: "Miguel O'Hara (voice)" },
    ],
  },
  {
    id: "the-batman",
    title: "The Batman",
    overview: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption.",
    posterPath: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1514565131-fce0801e5785?w=1200&auto=format&fit=crop&q=80",
    genres: ["Action", "Crime", "Drama"],
    durationMinutes: 176,
    rating: 7.9,
    language: "English",
    certificate: "UA 16+",
    releaseDate: "2022-03-04",
    basePrice: 300,
    isFeatured: true,
    isNowShowing: true,
    isUpcoming: false,
    format: ["2D", "Dolby Atmos"],
    director: "Matt Reeves",
    cast: [
      { name: "Robert Pattinson", role: "Bruce Wayne / Batman" },
      { name: "Zoë Kravitz", role: "Selina Kyle / Catwoman" },
      { name: "Paul Dano", role: "The Riddler" },
    ],
  },
  {
    id: "interstellar-re-release",
    title: "Interstellar: 10th Anniversary",
    overview: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft along with a team of researchers to find a new planet for humans.",
    posterPath: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=500&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1200&auto=format&fit=crop&q=80",
    genres: ["Sci-Fi", "Drama", "Adventure"],
    durationMinutes: 169,
    rating: 8.7,
    language: "English",
    certificate: "UA",
    releaseDate: "2024-09-15",
    basePrice: 350,
    isFeatured: false,
    isNowShowing: true,
    isUpcoming: false,
    format: ["IMAX 2D", "2D"],
    director: "Christopher Nolan",
    cast: [
      { name: "Matthew McConaughey", role: "Cooper" },
      { name: "Anne Hathaway", role: "Brand" },
      { name: "Jessica Chastain", role: "Murph" },
    ],
  },
  {
    id: "deadpool-and-wolverine",
    title: "Deadpool & Wolverine",
    overview: "Deadpool's peaceful existence comes crashing down when the Time Variance Authority recruits him to help safeguard the multiverse, partnering with a reluctant Wolverine.",
    posterPath: "https://images.unsplash.com/photo-1568832359672-e36cf5d74f54?w=500&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1200&auto=format&fit=crop&q=80",
    genres: ["Action", "Comedy", "Sci-Fi"],
    durationMinutes: 128,
    rating: 8.0,
    language: "Hindi",
    certificate: "A",
    releaseDate: "2024-07-26",
    basePrice: 320,
    isFeatured: false,
    isNowShowing: true,
    isUpcoming: false,
    format: ["3D", "2D", "4DX 3D"],
    director: "Shawn Levy",
    cast: [
      { name: "Ryan Reynolds", role: "Wade Wilson / Deadpool" },
      { name: "Hugh Jackman", role: "Logan / Wolverine" },
    ],
  },
  {
    id: "gladiator-ii",
    title: "Gladiator II",
    overview: "Years after witnessing the death of revered hero Maximus at the hands of his uncle, Lucius must enter the Colosseum after his home is conquered by the tyrannical Emperors.",
    posterPath: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=500&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=1200&auto=format&fit=crop&q=80",
    genres: ["Action", "Drama", "Adventure"],
    durationMinutes: 148,
    rating: 7.9,
    language: "English",
    certificate: "A",
    releaseDate: "2024-11-22",
    basePrice: 340,
    isFeatured: false,
    isNowShowing: false,
    isUpcoming: true,
    upcomingCategory: "this-weekend",
    format: ["2D", "IMAX 2D", "Insignia Luxe"],
    director: "Ridley Scott",
    cast: [
      { name: "Paul Mescal", role: "Lucius" },
      { name: "Pedro Pascal", role: "General Acacius" },
      { name: "Denzel Washington", role: "Macrinus" },
    ],
  },
  {
    id: "joker-folie-a-deux",
    title: "Joker: Folie à Deux",
    overview: "Failed comedian Arthur Fleck meets the love of his life, Harley Quinn, while incarcerated at Arkham State Hospital. Upon his release, the two embark on a doomed musical misadventure.",
    posterPath: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200&auto=format&fit=crop&q=80",
    genres: ["Drama", "Crime", "Thriller"],
    durationMinutes: 138,
    rating: 7.5,
    language: "Hindi",
    certificate: "A",
    releaseDate: "2024-10-04",
    basePrice: 300,
    isFeatured: false,
    isNowShowing: false,
    isUpcoming: true,
    upcomingCategory: "tomorrow",
    format: ["2D", "IMAX 2D"],
    director: "Todd Phillips",
    cast: [
      { name: "Joaquin Phoenix", role: "Arthur Fleck / Joker" },
      { name: "Lady Gaga", role: "Lee Quinzel / Harley Quinn" },
    ],
  },
  {
    id: "the-wild-robot",
    title: "The Wild Robot",
    overview: "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
    posterPath: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=80",
    genres: ["Animation", "Sci-Fi", "Family"],
    durationMinutes: 102,
    rating: 8.5,
    language: "Gujarati",
    certificate: "U",
    releaseDate: "2024-09-27",
    basePrice: 290,
    isFeatured: false,
    isNowShowing: false,
    isUpcoming: true,
    upcomingCategory: "today",
    format: ["3D", "2D"],
    director: "Chris Sanders",
    cast: [
      { name: "Lupita Nyong'o", role: "Roz (voice)" },
      { name: "Pedro Pascal", role: "Fink (voice)" },
      { name: "Kit Connor", role: "Brightbill (voice)" },
    ],
  },
  {
    id: "inside-out-2",
    title: "Inside Out 2",
    overview: "Joy, Sadness, Anger, Fear, and Disgust have been running a successful operation. But when Anxiety, Envy, Ennui, and Embarrassment arrive, everything is thrown into disarray.",
    posterPath: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=500&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200&auto=format&fit=crop&q=80",
    genres: ["Animation", "Comedy", "Family"],
    durationMinutes: 96,
    rating: 7.8,
    language: "English",
    certificate: "U",
    releaseDate: "2024-06-14",
    basePrice: 260,
    isFeatured: false,
    isNowShowing: true,
    isUpcoming: false,
    format: ["3D", "2D"],
    director: "Kelsey Mann",
    cast: [
      { name: "Amy Poehler", role: "Joy (voice)" },
      { name: "Maya Hawke", role: "Anxiety (voice)" },
      { name: "Phyllis Smith", role: "Sadness (voice)" },
    ],
  },
  {
    id: "knives-out-glass-onion",
    title: "Glass Onion: A Knives Out Mystery",
    overview: "Master detective Benoit Blanc travels to Greece to peel back the layers of a mystery involving a tech billionaire and his eclectic group of friends.",
    posterPath: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=500&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=1200&auto=format&fit=crop&q=80",
    genres: ["Comedy", "Thriller", "Crime"],
    durationMinutes: 139,
    rating: 7.2,
    language: "English",
    certificate: "UA 13+",
    releaseDate: "2022-12-23",
    basePrice: 250,
    isFeatured: false,
    isNowShowing: true,
    isUpcoming: false,
    format: ["2D"],
    director: "Rian Johnson",
    cast: [
      { name: "Daniel Craig", role: "Benoit Blanc" },
      { name: "Edward Norton", role: "Miles Bron" },
      { name: "Janelle Monáe", role: "Helen Brand" },
    ],
  },
  {
    id: "a-quiet-place-day-one",
    title: "A Quiet Place: Day One",
    overview: "A young woman named Sam must navigate a claustrophobic and harrowing invasion of New York City by bloodthirsty alien creatures with ultra-sensitive hearing.",
    posterPath: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1514565131-fce0801e5785?w=1200&auto=format&fit=crop&q=80",
    genres: ["Thriller", "Sci-Fi", "Drama"],
    durationMinutes: 99,
    rating: 6.9,
    language: "English",
    certificate: "UA 16+",
    releaseDate: "2024-06-28",
    basePrice: 270,
    isFeatured: false,
    isNowShowing: true,
    isUpcoming: false,
    format: ["2D", "Dolby Atmos"],
    director: "Michael Sarnoski",
    cast: [
      { name: "Lupita Nyong'o", role: "Samira" },
      { name: "Joseph Quinn", role: "Eric" },
      { name: "Alex Wolff", role: "Reuben" },
    ],
  },
];
